Collapse expand all
reach-u/react-json-view pull request #6
Opened 2021-02-11 15:32 UTC by georgkaru

2021-02-16 07:10 UTC, KristerL commented on dev-server/src/index.js
> -class DevDemo extends React.PureComponent {
See devdemo, niiet rakendust ei sega iseeneset, aga miks PureComponenti asendasid Componentiga?

2021-02-16 07:20 UTC, KristerL requested changes

2021-02-16 07:20 UTC, KristerL commented on dev-server/src/index.js
> +                    shouldCollapse={({ src, namespace, type }) => {
Kas see ei ole loogika, mis peaks juba JsonVieweri sees olema? Hetkel peaks selle shouldCollapse loogika igal pool käsitsi välja kirjutama

2021-02-16 07:20 UTC, KristerL commented on src/js/components/DataTypes/Object.js
> +        if (!nextProps.jsvRoot) {
Siin võiks vb mõned kommentid panna, et mis toimub ja mis on mis.

2021-02-16 07:20 UTC, KristerL commented on src/js/components/DataTypes/Object.js
> +                if (nextProps.collapsed === 1) {
siin saaks lühemalt:
`AttributeStore.set(nextProps.rjvId, nextProps.namespace, 'expanded', !nextProps.collapsed === 1);`

2021-02-16 07:20 UTC, KristerL commented on test/tests/js/components/DataTypes/Object-test.js
> -                collapsed={true}
Idee poolest testid võiks ju edasi töötada ka siis kui default behavior muutub. Collapsed on ju props, mida saab edasi passida ja mida võibolla keegi tulevikus kasutab. Või collapsed saabki by default ainult 1 olla? Siis tuleks ta üldse ära võtta

Testide üle kirjutamine on pigem halb märk ja võib viitada sellele et midagi on valesti. Vanad testid võiks tööle jääda ja uued võiks peale kirjutada.

2021-02-17 07:47 UTC, georgkaru commented on dev-server/src/index.js
> -class DevDemo extends React.PureComponent {
Et kasutataks imporditud { Component }, aga ei pea otseselt

2021-02-26 09:57 UTC, KristerL requested changes

2021-02-26 09:57 UTC, KristerL commented on dev-server/src/index.js
> +                    enableClipboard={true}
inconsistent spacing

2021-02-26 09:57 UTC, KristerL commented on src/js/components/PasteToJson.js
> +            [...namespace].splice(0, namespace.length-1),
Äkki võiks selle eraldi muutujaks teha. Nimi või comment võiks siis korra seletada, miks namespace nii võtta

2021-02-26 09:57 UTC, KristerL commented on src/js/components/PasteToJson.js
> +        const dropTargetIdx = pastedOnObjectOrArray && parent_type !== 'array' ?
Kas siin tegelt ei saaks koguaeg existingValuest otsida? Kas ainult array korral peab existing value olema parenti sisu?

2021-02-26 09:57 UTC, KristerL commented on src/js/components/PasteToJson.js
> +        const request = {
Äkki oleks loetavuse mõttes mõtekas teha kaks requesti? Üks siis selle olukorra jaoks, kui on pastedOnObjectOrArray ja teine selle jaoks, kui on teised olukorrad? Siin võibolla oleks ka hea seletav kommentaar, et kui on pastedOnObjectOrArray, siis tuleb võtta tegelt parenti sisu ja sellepärast minnakse namespaceis alati 1 samm rohkem tagasi kui muidu

2021-02-26 09:57 UTC, KristerL commented on src/js/components/PasteToJson.js
> +                // part of the array before the specified index
Siit võib commentid ära võtta, kuna kood seletab ise juba ennast

2021-02-26 09:57 UTC, KristerL commented on src/js/components/VariableEditor.js
> +                { onEdit !== false && editMode === false
Siin ja allpool saaksid ? ... : null asemel kasutada lihtsalt && check-i. Siis ei ole null-i vaja

2021-02-26 09:57 UTC, KristerL commented on src/js/components/VariableMeta.js
> +                { enableClipboard && !jsvRoot ? (
&&

2021-02-26 10:07 UTC, georgkaru commented on src/js/components/PasteToJson.js
> +        const dropTargetIdx = pastedOnObjectOrArray && parent_type !== 'array' ?
Saab teha selliselt, et paste objekti või array peal kasutab existing valuet. Variable peale paste'ides tuleb kasutada src, sest variable'i jaoks see src on juba see, kus sees ta on.

2021-02-26 10:38 UTC, KristerL commented on src/js/components/PasteToJson.js
> +        const dropTargetIdx = pastedOnObjectOrArray && parent_type !== 'array' ?
Aga existing value ei anna seda, kus ta sees on?

2021-02-26 10:52 UTC, merged